apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-release
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmkmou/jenkins-k8s.git'
    path: release
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true